name: Publish to nuget
on:
  push:
    branches:
      - main # Default release branch
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.x'
          
      - name: Automated Version Bump
        # You may pin to the exact commit or the version.
        # uses: phips28/gh-action-bump-version@bbd196e988e4612476d63b183ab1146db423e4d2
        uses: phips28/gh-action-bump-version@v8.0.18
        with:
          # Prefix that is used for the git tag
          tag-prefix: 'v'
          
      - name: Git Version
        id: version
        uses: codacy/git-version@2.4.0
        with:
          release-branch: main

      # Publish
      - name: Publish NuGet
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
          PROJECT_FILE_PATH: GameAssistant/GameAssistant.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_STATIC: ${{ steps.version.outputs.version }}
          
